language: node_js
node_js:
- '8'
before_deploy:
- npm run build
deploy:
  provider: heroku
  app: event-manager-tw
  api_key:
    secure: eH52OR5N82inkhAI5JZwpkmwCRGajCIoQlYerzJOY91FTyewr3Ibam8pfYDE9hP1l5P3WkC4klhWgPxRSKPWVN4VdoDTAfS9GU43wzFTQ7yxENz/RLTa4svZ5HFbIih+y5V0TEhAwgZr82bqCZMc0L3Hs1E2mo/9huvFqnSSExoYqcpYxmW5BxvtGdICEnk006nkjbOrluLF14ovjczExIpe8LBa+DcXQ+0B9IpzBNHpoZgTO4ldGL+xfATl21bmBmZ6vuEC2lgQw8Xqmm6DkJj4miuOyACu/ESXtkmEYKhyE//v7PtOUfvbV24CmBvTTVvC0bnPkqj6r1zDOxJ/1H00my/ZbU4JwXzXCfqPB23rVd9BjIygi7tBntiwf+ol/LCEA6FT44HvoUHNq+yNuYpHGT1Fd2BlxcCbRNnm5Nb54SjpEjpacHmc3aMUvjr9W9vu1bmifH6Swl9cajq6IfzMtHIaUnulWjNIRcTQuTpIGyMfKJqRdPJ9HviI5d9ZnhpeNFoXzz/C1kQ67+7FqdbrUn6a07ybM3LY7aCv30juu6so6IevAfgAJ1ofHgm6YBVAf0kmiGDe/R43Nee5BgqFOSRdgM8EoYNSiOjTYaFcub7Vf4tBAwQR4QIOy99jRm7j0fc5gKksOK4tnYSrk9MU9zkBJrI3PolQu3ERvqY=
